In [23]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 5.8 MB/s eta 0:00:00 MB/s eta 0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [24]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

In [4]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [5]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [6]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor

In [8]:
X = df.drop(columns=['price'])
y = df['price']

In [9]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

## Ordinal Encoding

In [10]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [11]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode)
    ], 
    remainder='passthrough'
)

In [12]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [13]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [14]:
scores.mean(),scores.std()

(np.float64(0.7363096633436828), np.float64(0.03238005754429932))

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [16]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [17]:
y_pred = pipeline.predict(X_test)

In [18]:
y_pred = np.expm1(y_pred)

In [19]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089367

In [20]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [25]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [26]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [27]:
model_output

[['linear_reg', np.float64(0.7363096633436828), 0.9463822160089367],
 ['svr', np.float64(0.764207913354413), 0.8472636473483927],
 ['ridge', np.float64(0.7363125343993554), 0.946338774185338],
 ['LASSO', np.float64(0.05943378064493572), 1.528905986892753],
 ['decision tree', np.float64(0.7716058633886688), 0.751295790845806],
 ['random forest', np.float64(0.8809412534838043), 0.5298727726894275],
 ['extra trees', np.float64(0.8677966297475528), 0.5551301874112944],
 ['gradient boosting', np.float64(0.8725671311403618), 0.576197320884159],
 ['adaboost', np.float64(0.7560657959916128), 0.825432865979269],
 ['mlp', np.float64(0.7988289703915962), 0.7175743539605418],
 ['xgboost', np.float64(0.8894876835260124), 0.5040475180464287]]

In [28]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [29]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.889488  0.504048
5       random forest  0.880941  0.529873
6         extra trees  0.867797  0.555130
7   gradient boosting  0.872567  0.576197
9                 mlp  0.798829  0.717574
4       decision tree  0.771606  0.751296
8            adaboost  0.756066  0.825433
1                 svr  0.764208  0.847264
2               ridge  0.736313  0.946339
0          linear_reg  0.736310  0.946382
3               LASSO  0.059434  1.528906

## OneHotEncoding

In [30]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first'),['sector','agePossession','furnishing_type'])
    ], 
    remainder='passthrough'
)

In [31]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [32]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [33]:
scores.mean()

np.float64(0.8546135292623269)

In [34]:
scores.std()

np.float64(0.015997794263816388)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [36]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first'),
                                                  ['sector', 'agePossession',
                                                   'furnishing_type'])])),
                ('regressor', LinearRegression())])

In [37]:
y_pred = pipeline.predict(X_test)

In [38]:
y_pred = np.expm1(y_pred)

In [39]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.6497426558119209

In [40]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [41]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [42]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [43]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [44]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.895047  0.471750
10            xgboost  0.895850  0.493456
5       random forest  0.891358  0.494256
9                 mlp  0.877231  0.529630
7   gradient boosting  0.876580  0.570731
0          linear_reg  0.854614  0.649743
2               ridge  0.854686  0.652804
4       decision tree  0.807605  0.684715
8            adaboost  0.754895  0.827166
1                 svr  0.769741  0.834124
3               LASSO  0.059434  1.528906

## OneHotEncoding With PCA

In [45]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [46]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=0.95)),
    ('regressor', LinearRegression())
])

In [47]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [48]:
scores.mean()

np.float64(0.06225201431451137)

In [49]:
scores.std()

np.float64(0.019860594071640092)

In [50]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [51]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [52]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [53]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [54]:
model_df.sort_values(['mae'])

                 name        r2       mae
5       random forest  0.761660  0.649341
6         extra trees  0.738560  0.697065
4       decision tree  0.696442  0.761509
10            xgboost  0.622205  0.967581
7   gradient boosting  0.610623  0.987906
1                 svr  0.218045  1.361141
9                 mlp  0.208642  1.396388
8            adaboost  0.306823  1.452015
2               ridge  0.062252  1.526707
0          linear_reg  0.062252  1.526707
3               LASSO  0.059676  1.528739

## Target Encoder

In [56]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: statsmodels>=0.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /opt/anaconda3/lib/python3.13/site-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0
Note: you may need to restart the kernel to use updated packages.

In [57]:
import category_encoders as ce

columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [58]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [59]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [60]:
scores.mean(),scores.std()

(np.float64(0.829521918225536), np.float64(0.018384463379122813))

In [61]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [62]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [63]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [64]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [65]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.904798  0.447518
5       random forest  0.901188  0.453822
6         extra trees  0.902026  0.454068
7   gradient boosting  0.888992  0.507683
4       decision tree  0.830696  0.575356
9                 mlp  0.851656  0.613938
8            adaboost  0.817719  0.711949
0          linear_reg  0.829522  0.713011
2               ridge  0.829536  0.713523
1                 svr  0.782917  0.818851
3               LASSO  0.059434  1.528906

# Hyperparameter Tuning

In [66]:
from sklearn.model_selection import GridSearchCV

In [67]:
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': ['auto', 'sqrt']
}

In [68]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [69]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor())
])

In [70]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [71]:
search = GridSearchCV(pipeline, param_grid, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [72]:
search.fit(X, y_transformed)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.864 total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.856 total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.873 total time=   0.1s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.873 total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.871 total time=   0.1s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.871 total time=   0.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.903 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.909 total time=   0.1s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.897 total time=   0.2s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.890 total time=   0.2s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.881 total time=   0.2s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.881 total time=   0.2s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.907 total time=   0.4s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.924 total time=   0.3s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.904 total time=   0.4s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.888 total time=   0.3s

Exception ignored in: <function ResourceTracker.__del__ at 0x1071edbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
/opt/anaconda3/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.872 total time=   0.1s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.847 total time=   0.1s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.867 total time=   0.1s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.863 total time=   0.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.893 total time=   0.3s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.878 total time=   0.3s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.888 total time=   0.3s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.881 total time=   0.4s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.889 total time=   0.3s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.888 total time=   0.3s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.880 total time=   0.3s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.875 total time=   0.3s

Exception ignored in: <function ResourceTracker.__del__ at 0x104971bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.887 total time=   0.1s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.879 total time=   0.1s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.889 total time=   0.1s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.877 total time=   0.1s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.886 total time=   0.3s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.879 total time=   0.2s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.890 total time=   0.2s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.887 total time=   0.2s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.877 total time=   0.2s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.873 total time=   0.2s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.905 total time=   0.4s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.913 total time=   0.3s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.868 total time=   0.2s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.863 total time=   0.1s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.875 total time=   0.1s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.875 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.862 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.857 total time=   0.1s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.890 total time=   0.2s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.891 total time=   0.2s

Exception ignored in: <function ResourceTracker.__del__ at 0x105741bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.892 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.899 total time=   0.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.875 total time=   0.1s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.858 total time=   0.1s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.898 total time=   0.4s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.888 total time=   0.3s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.895 total time=   0.3s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.893 total time=   0.3s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.887 total time=   0.3s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.879 total time=   0.4s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.908 total time=   0.5s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.924 total time=   0.5s

Exception ignored in: <function ResourceTracker.__del__ at 0x105219bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.877 total time=   0.2s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.875 total time=   0.2s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.862 total time=   0.2s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.864 total time=   0.2s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.902 total time=   0.3s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.898 total time=   0.3s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.885 total time=   0.3s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.885 total time=   0.2s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.910 total time=   0.5s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.928 total time=   0.5s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.909 total time=   0.5s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.897 total time=   0.5s

Exception ignored in: <function ResourceTracker.__del__ at 0x11006dbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.864 total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.860 total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.893 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.899 total time=   0.1s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.887 total time=   0.1s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.887 total time=   0.1s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.880 total time=   0.1s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.872 total time=   0.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.901 total time=   0.3s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.916 total time=   0.2s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.894 total time=   0.2s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.881 total time=   0.3s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.871 total time=   0.1s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.865 total time=   0.1s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.875 total time=   0.1s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.874 total time=   0.2s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.904 total time=   0.5s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.890 total time=   0.5s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.898 total time=   0.5s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.888 total time=   0.5s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.895 total time=   0.5s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.894 total time=   0.5s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.881 total time=   0.5s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.884 total time=   0.4s

Exception ignored in: <function ResourceTracker.__del__ at 0x105661bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.877 total time=   0.3s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.856 total time=   0.2s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.867 total time=   0.2s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.863 total time=   0.2s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.906 total time=   0.5s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.895 total time=   0.5s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.901 total time=   0.5s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.898 total time=   0.5s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.888 total time=   0.5s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.886 total time=   0.5s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.911 total time=   0.7s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.927 total time=   0.6s

Exception ignored in: <function ResourceTracker.__del__ at 0x107585bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.902 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.911 total time=   0.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.899 total time=   0.1s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.875 total time=   0.1s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.880 total time=   0.1s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.872 total time=   0.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.908 total time=   0.2s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.924 total time=   0.2s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.903 total time=   0.2s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.888 total time=   0.2s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.896 total time=   0.2s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.882 total time=   0.2s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.858 total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.855 total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.888 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.891 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.875 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.850 total time=   0.1s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.864 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.861 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.874 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.867 total time=   0.1s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.896 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.909 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.891 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.867 total time=   0.1s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.883 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.868 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.873 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.871 total time=   0.1s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.902 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.915 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.894 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.880 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s

Exception ignored in: <function ResourceTracker.__del__ at 0x107075bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.892 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.900 total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.875 total time=   0.1s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.852 total time=   0.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.895 total time=   0.1s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.876 total time=   0.1s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.884 total time=   0.1s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.885 total time=   0.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.907 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.927 total time=   0.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.907 total time=   0.2s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.896 total time=   0.2s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.903 total time=   0.1s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.890 total time=   0.1s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.902 total time=   0.1s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.895 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.883 total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.897 total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.875 total time=   0.0s

Exception ignored in: <function ResourceTracker.__del__ at 0x104959bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.887 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.876 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.879 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.873 total time=   0.1s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.902 total time=   0.2s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.917 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.904 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.886 total time=   0.2s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.895 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.880 total time=   0.1s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.871 total time=   0.1s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.872 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.857 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.859 total time=   0.1s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.891 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.891 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.872 total time=   0.2s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.852 total time=   0.1s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.881 total time=   0.2s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.875 total time=   0.2s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.890 total time=   0.2s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.882 total time=   0.2s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.874 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.873 total time=   0.2s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.899 total time=   0.2s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.907 total time=   0.2s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.892 total time=   0.3s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.882 total time=   0.3s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.898 total time=   0.3s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.889 total time=   0.3s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.883 total time=   0.3s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.879 total time=   0.3s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.904 total time=   0.5s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.918 total time=   0.5s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.866 total time=   0.1s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.873 total time=   0.1s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.901 total time=   0.1s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.913 total time=   0.1s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.884 total time=   0.2s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.880 total time=   0.2s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.890 total time=   0.2s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.885 total time=   0.2s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.897 total time=   0.5s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.894 total time=   0.4s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.885 total time=   0.5s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.881 total time=   0.5s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.910 total time=   0.1s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.927 total time=   0.1s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.906 total time=   0.1s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.892 total time=   0.1s

Exception ignored in: <function ResourceTracker.__del__ at 0x102aa5bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.859 total time=   0.1s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.860 total time=   0.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.892 total time=   0.2s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.893 total time=   0.2s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.887 total time=   0.1s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.890 total time=   0.2s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.908 total time=   0.3s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.927 total time=   0.4s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.909 total time=   0.3s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.892 total time=   0.2s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.903 total time=   0.2s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.893 total time=   0.3s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.892 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.904 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.887 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.876 total time=   0.1s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.875 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.865 total time=   0.1s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.881 total time=   0.1s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.883 total time=   0.1s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.885 total time=   0.1s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.884 total time=   0.1s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.873 total time=   0.1s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.865 total time=   0.1s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.899 total time=   0.2s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.911 total time=   0.2s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.891 total time=   0.2s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.871 total time=   0.2s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.901 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.915 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.900 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.891 total time=   0.1s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.892 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.883 total time=   0.1s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.896 total time=   0.1s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.892 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.904 total time=   0.4s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.889 total time=   0.4s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.893 total time=   0.4s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.886 total time=   0.4s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.898 total time=   0.5s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.889 total time=   0.5s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.880 total time=   0.5s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.879 total time=   0.5s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.906 total time=   0.3s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.922 total time=   0.4s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.905 total time=   0.3s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.889 total time=   0.3s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.894 total time=   0.3s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.890 total time=   0.3s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.899 total time=   0.3s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.891 total time=   0.4s

Exception ignored in: <function ResourceTracker.__del__ at 0x104b8dbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.896 total time=   0.1s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.915 total time=   0.1s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.893 total time=   0.1s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.882 total time=   0.1s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.881 total time=   0.1s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.877 total time=   0.1s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.885 total time=   0.1s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.879 total time=   0.1s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.862 total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.857 total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.893 total time=   0.1s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.892 total time=   0.1s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.893 total time=   0.1s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.899 total time=   0.1s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.875 total time=   0.1s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.855 total time=   0.2s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.878 total time=   0.2s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.852 total time=   0.2s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.870 total time=   0.2s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.866 total time=   0.2s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.904 total time=   0.2s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.914 total time=   0.2s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.892 total time=   0.2s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.879 total time=   0.2s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.881 total time=   0.4s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.882 total time=   0.3s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.908 total time=   0.5s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.924 total time=   0.4s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.904 total time=   0.5s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.889 total time=   0.5s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.899 total time=   0.5s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.885 total time=   0.4s

Exception ignored in: <function ResourceTracker.__del__ at 0x106f89bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.902 total time=   0.7s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.896 total time=   0.7s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.889 total time=   0.7s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.886 total time=   0.7s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s

Exception ignored in: <function ResourceTracker.__del__ at 0x1060ddbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.892 total time=   0.2s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.873 total time=   0.2s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.882 total time=   0.2s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.876 total time=   0.2s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.886 total time=   0.3s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.881 total time=   0.3s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.872 total time=   0.3s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.871 total time=   0.3s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.895 total time=   0.1s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.883 total time=   0.1s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.875 total time=   0.1s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.872 total time=   0.1s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.892 total time=   0.3s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.886 total time=   0.3s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.879 total time=   0.3s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.875 total time=   0.3s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.906 total time=   0.1s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.921 total time=   0.1s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.907 total time=   0.1s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.880 total time=   0.1s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.894 total time=   0.2s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.886 total time=   0.2s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.881 total time=   0.2s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.878 total time=   0.2s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.906 total time=   0.3s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.918 total time=   0.3s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.906 total time=   0.3s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.886 total time=   0.3s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.913 total time=   0.5s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.926 total time=   0.4s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.909 total time=   0.4s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.898 total time=   0.5s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.905 total time=   0.4s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.893 total time=   0.4s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.900 total time=   0.4s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.897 total time=   0.4s

Exception ignored in: <function ResourceTracker.__del__ at 0x10846dbc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 5/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.887 total time=   0.2s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.877 total time=   0.2s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.893 total time=   0.3s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.887 total time=   0.3s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.874 total time=   0.2s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.875 total time=   0.3s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.903 total time=   0.4s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.914 total time=   0.3s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.905 total time=   0.2s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.887 total time=   0.1s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.899 total time=   0.2s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.880 total time=   0.1s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.896 total time=   0.1s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.891 total time=   0.2s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.883 total time=   0.2s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.879 total time=   0.2s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.873 total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.859 total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.875 total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.870 total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.878 total time=   0.1s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.873 total time=   0.1s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.859 total time=   0.1s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.863 total time=   0.1s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.858 total time=   0.1s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.860 total time=   0.2s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.891 total time=   0.2s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.895 total time=   0.2s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.896 total time=   0.1s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.910 total time=   0.1s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.889 total time=   0.1s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.880 total time=   0.1s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.890 total time=   0.1s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.874 total time=   0.1s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.888 total time=   0.1s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.876 total time=   0.1s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.894 total time=   0.3s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.875 total time=   0.3s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.887 total time=   0.3s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.881 total time=   0.3s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.890 total time=   0.4s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.890 total time=   0.4s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.913 total time=   0.7s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.928 total time=   0.7s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.911 total time=   0.7s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.897 total time=   0.6s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.905 total time=   0.6s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.894 total time=   0.7s

Exception ignored in: <function ResourceTracker.__del__ at 0x1050e9bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 1/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.899 total time=   0.1s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.885 total time=   0.1s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.893 total time=   0.1s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.889 total time=   0.1s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.885 total time=   0.1s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.880 total time=   0.1s
[CV 1/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.904 total time=   0.2s
[CV 2/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.923 total time=   0.2s
[CV 3/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.906 total time=   0.2s
[CV 4/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.892 total time=   0.2s
[CV 5/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.906 total time=   0.2s
[CV 6/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.895 total time=   0.2s
[CV 7/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.901 total time=   0.2s
[CV 8/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.893 total time=   0.3s
[CV 9/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.892 total time=   0.2s
[CV 10/10] END regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.888 total time=   0.2s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.865 total time=   0.1s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.863 total time=   0.1s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.889 total time=   0.2s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.899 total time=   0.2s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.880 total time=   0.1s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.873 total time=   0.1s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.885 total time=   0.1s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.882 total time=   0.1s
[CV 9/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.871 total time=   0.1s
[CV 10/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.864 total time=   0.1s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.903 total time=   0.1s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.911 total time=   0.1s
[CV 1/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.911 total time=   0.3s
[CV 2/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.923 total time=   0.3s
[CV 3/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.905 total time=   0.3s
[CV 4/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.889 total time=   0.3s
[CV 5/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.897 total time=   0.3s
[CV 6/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.887 total time=   0.3s
[CV 7/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.897 total time=   0.3s
[CV 8/10] END regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.893 total time=   0.3s

Exception ignored in: <function ResourceTracker.__del__ at 0x109731bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning:
640 fits failed out of a total of 1280.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
379 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/pipeline.py", line 663, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
261 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/pipeline.py", line 663, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.87077596 0.87006412
 0.87269925 0.87251627 0.88606509 0.88769312 0.88820514 0.88900926
 0.89267176 0.89484994 0.89635801 0.89678348 0.90036704 0.90018303
 0.90178385 0.90147838        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.86925704 0.86888743 0.87052028 0.87096269 0.88039786 0.88216636
 0.88463512 0.88394396 0.88530213 0.88779976 0.8888704  0.88982463
 0.89229461 0.89237141 0.89370558 0.89399381        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.87052593 0.87119021 0.8719561  0.87220775
 0.88256466 0.88683302 0.88733896 0.88836531 0.89452668 0.89463814
 0.89585396 0.89655701 0.8989968  0.90091219 0.90208413 0.90212959
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.86979254 0.87135233
 0.87317295 0.87261241 0.88246776 0.88734498 0.8875329  0.88882034
 0.8924635  0.89588482 0.89690418 0.89675682 0.90084537 0.90076395
 0.90209644 0.90241031]
  warnings.warn(

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedRoom',
                                                                          'bathroom',
                                                                          'built_up_area',
                                                                          'servant '
                                                                          'room',
                                                                          'store '
                                                                          'room']),
                                                                        ('cat',
                                                                         OrdinalEncoder(),
                                                                         ['property_type',
                                                                          'sector',
                                                                          'balcony',
                                                                          'agePossession',
                                                                          'furnishing_type',...
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         ['agePossession']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['sector'])])),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=-1,
             param_grid={'regressor__max_depth': [None, 10, 20, 30],
                         'regressor__max_features': ['auto', 'sqrt'],
                         'regressor__max_samples': [0.1, 0.25, 0.5, 1.0],
                         'regressor__n_estimators': [50, 100, 200, 300]},
             scoring='r2', verbose=4)

In [73]:
final_pipe = search.best_estimator_

In [74]:
search.best_params_

{'regressor__max_depth': 30,
 'regressor__max_features': 'sqrt',
 'regressor__max_samples': 1.0,
 'regressor__n_estimators': 300}

In [75]:
search.best_score_

np.float64(0.9024103113057633)

In [76]:
final_pipe.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePossession']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_depth=30, max_features='sqrt',
                                       max_samples=1.0, n_estimators=300))])

## Exporting the Model

In [77]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [78]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=500))
])

In [79]:
pipeline.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sector',
                                                   'agePossession'])])),
                ('regressor', RandomForestRegressor(n_estimators=500))])

In [80]:
import pickle

with open('pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

In [81]:
with open('df.pkl', 'wb') as file:
    pickle.dump(X, file)

In [82]:
X

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,2.0,2.0,1,Relatively New,532.0,0.0,0.0,unfurnished,Medium,Mid Floor
3550,house,sector 109,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,unfurnished,High,Low Floor
3551,flat,sector 2,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,semifurnished,Medium,Mid Floor
3552,house,sector 43,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,unfurnished,Medium,Mid Floor
3553,flat,sector 68,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,semifurnished,Medium,High Floor

## Trying out the predictions

In [83]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='object')

In [84]:
X.iloc[0].values

array(['flat', 'sector 36', np.float64(3.0), np.float64(2.0), '2',
       'New Property', np.float64(850.0), np.float64(0.0),
       np.float64(0.0), 'unfurnished', 'Low', 'Low Floor'], dtype=object)

In [85]:
data = [['house', 'sector 102', 4, 3, '3+', 'New Property', 2750, 0, 0, 'unfurnished', 'Low', 'Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']

# Convert to DataFrame
one_df = pd.DataFrame(data, columns=columns)

one_df

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,house,sector 102,4,3,3+,New Property,2750,0,0,unfurnished,Low,Low Floor

In [86]:
np.expm1(pipeline.predict(one_df))

array([3.08094])

In [87]:
X.dtypes

property_type       object
sector              object
bedRoom            float64
bathroom           float64
balcony             object
agePossession       object
built_up_area      float64
servant room       float64
store room         float64
furnishing_type     object
luxury_category     object
floor_category      object
dtype: object

In [88]:
sorted(X['sector'].unique().tolist())

['dwarka expressway',
 'gwal pahari',
 'manesar',
 'sector 1',
 'sector 10',
 'sector 102',
 'sector 103',
 'sector 104',
 'sector 105',
 'sector 106',
 'sector 107',
 'sector 108',
 'sector 109',
 'sector 11',
 'sector 110',
 'sector 111',
 'sector 112',
 'sector 113',
 'sector 12',
 'sector 13',
 'sector 14',
 'sector 15',
 'sector 17',
 'sector 2',
 'sector 21',
 'sector 22',
 'sector 23',
 'sector 24',
 'sector 25',
 'sector 26',
 'sector 27',
 'sector 28',
 'sector 3',
 'sector 30',
 'sector 31',
 'sector 33',
 'sector 36',
 'sector 37',
 'sector 37d',
 'sector 38',
 'sector 39',
 'sector 4',
 'sector 40',
 'sector 41',
 'sector 43',
 'sector 45',
 'sector 46',
 'sector 47',
 'sector 48',
 'sector 49',
 'sector 5',
 'sector 50',
 'sector 51',
 'sector 52',
 'sector 53',
 'sector 54',
 'sector 55',
 'sector 56',
 'sector 57',
 'sector 58',
 'sector 59',
 'sector 6',
 'sector 60',
 'sector 61',
 'sector 62',
 'sector 63',
 'sector 63a',
 'sector 65',
 'sector 66',
 'sector 67',
 'sector 67a',
 'sector 68',
 'sector 69',
 'sector 7',
 'sector 70',
 'sector 70a',
 'sector 71',
 'sector 72',
 'sector 73',
 'sector 74',
 'sector 76',
 'sector 77',
 'sector 78',
 'sector 79',
 'sector 8',
 'sector 80',
 'sector 81',
 'sector 82',
 'sector 82a',
 'sector 83',
 'sector 84',
 'sector 85',
 'sector 86',
 'sector 88',
 'sector 88a',
 'sector 89',
 'sector 9',
 'sector 90',
 'sector 91',
 'sector 92',
 'sector 93',
 'sector 95',
 'sector 99',
 'sohna road']